[package]
name = "game_of_live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
piston_window = "0.131.0"
piston2d-graphics = "0.44.0"
piston2d-opengl_graphics = "0.84.0"
